-- MySQL Script generated by MySQL Workbench
-- Thu Jan 16 22:54:47 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema escape_sorbonne
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema escape_sorbonne
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escape_sorbonne` DEFAULT CHARACTER SET utf8 ;
USE `escape_sorbonne` ;

-- -----------------------------------------------------
-- Table `escape_sorbonne`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escape_sorbonne`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(45) NULL,
  `mail` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escape_sorbonne`.`personages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escape_sorbonne`.`personages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `Desc` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escape_sorbonne`.`indices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escape_sorbonne`.`indices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `in` VARCHAR(75) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escape_sorbonne`.`enigmes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escape_sorbonne`.`enigmes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `en` MEDIUMTEXT NULL,
  `indices_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_enigmes_indices_idx` (`indices_id` ASC) VISIBLE,
  CONSTRAINT `fk_enigmes_indices`
    FOREIGN KEY (`indices_id`)
    REFERENCES `escape_sorbonne`.`indices` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escape_sorbonne`.`lieux`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escape_sorbonne`.`lieux` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(70) NULL,
  `Desc` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escape_sorbonne`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escape_sorbonne`.`article` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(255) NULL,
  `texte` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escape_sorbonne`.`lieux_has_personages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escape_sorbonne`.`lieux_has_personages` (
  `lieux_id` INT NOT NULL,
  `personages_id` INT NOT NULL,
  PRIMARY KEY (`lieux_id`, `personages_id`),
  INDEX `fk_lieux_has_personages_personages1_idx` (`personages_id` ASC) VISIBLE,
  INDEX `fk_lieux_has_personages_lieux1_idx` (`lieux_id` ASC) VISIBLE,
  CONSTRAINT `fk_lieux_has_personages_lieux1`
    FOREIGN KEY (`lieux_id`)
    REFERENCES `escape_sorbonne`.`lieux` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lieux_has_personages_personages1`
    FOREIGN KEY (`personages_id`)
    REFERENCES `escape_sorbonne`.`personages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
